title: Billy Chua # your name (or website title) here
logo: "/images/WorkPhotoSideV1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Platform used
  <br><br>
  MSSQL,
  SQLite,
  Excel,
  Power BI
  
  <br><br>
  Experiences
  <br><br>
  Worked in Supply Chain Planning with 7 years of experience in analysis and inventory planning. 
  <br><br>
  Well versed in reporting, operational tasks and creating dashboards.
  <br><br>
  <a href="https://www.linkedin.com/in/billy-chua-1268a8a6/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
